language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "12"
deploy:
  provider: script
  script: npm i && npm run deploy
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
